### ISSUE TITLE
能够修改编译参数吗?

### ISSUE THREAD

**Issue by coney** [blade-build/blade-build#91]
比如加入-Wno-unused-local-typedefs等

**Comment by LiamHuang0205** [comment]
@chen3feng 
如何增加全局的编译选项呢？比如我要在全局打开 Cpp 11 标准的支持，目前的做法是在 `BLADE_ROOT` 文件中做如下修改：

    cc_config (
        extra_cppflags = [
            '-std=c++11',
        ],  
    )

但是 Blade 提示：`cc_config: unknown config item name: extra_cppflags`。

请问应该怎么办。谢谢！

**Comment by c9n** [comment]
@LiamHuang0205 

```
cc_config (
    cpp_flags = [
        '-std=c++11',
    ],  
)
```

试试
