### ISSUE TITLE
如果我想写一个类似make install之类的功能, 应该写一个什么样的target呢?

### ISSUE THREAD

**Issue by coney** [blade-build/blade-build#96]
使用gen_rule写了一个简单的规则, 但是好像运行后并没有在/tmp下创建文件

```
gen_rule(
  name = "install",
  cmd = "touch /tmp/tt.tt",
  deps = [":smsgd"],
  outs = ["/tmp/tt.tt"]
)
```

我想要的功能就是简单的把编译生成的程序拷到某个地方

**Comment by chen3feng** [comment]
> 最新的 blade 2.0 支持类似 make install 将当前工程项目打包成 include 和 lib 的库文件吗？

我觉得比较难以实现：

用 autotools 构建的项目通常都独立的完整的小项目，一般是一个或者最多几个库，外部依赖也是基于 autotools 构建的库。
但是 blade 及其类似的工具是把一个仓库中的多个构建目标作为一个依赖树来构建的，单独的一个库及其依赖如果要 install，
那么要么合并成一个库，这样导出的多个库不可避免地会带来库重复的冲突。要么按依赖拆分成很多很多细粒度的库来安装，也不好维护。
